config/routes.rb
MoviesAppTwo::Application.routes.draw do
  resources :movies_players


  resources :players


  resources :movies


  resources :roles


  resources :studios


  resources :genres

  root to: 'movies#index'

end

app/models/studio.rb
class Studio < ActiveRecord::Base
  attr_accessible :name, :movie_ids
  has_many :movies
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  # GET /studios
  # GET /studios.json
  def index
    @studios = Studio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @studios }
    end
  end

  # GET /studios/1
  # GET /studios/1.json
  def show
    @studio = Studio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @studio }
    end
  end

  # GET /studios/new
  # GET /studios/new.json
  def new
    @studio = Studio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @studio }
    end
  end

  # GET /studios/1/edit
  def edit
    @studio = Studio.find(params[:id])
  end

  # POST /studios
  # POST /studios.json
  def create
    @studio = Studio.new(params[:studio])

    respond_to do |format|
      if @studio.save
        format.html { redirect_to @studio, notice: 'Studio was successfully created.' }
        format.json { render json: @studio, status: :created, location: @studio }
      else
        format.html { render action: "new" }
        format.json { render json: @studio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /studios/1
  # PUT /studios/1.json
  def update
    @studio = Studio.find(params[:id])

    respond_to do |format|
      if @studio.update_attributes(params[:studio])
        format.html { redirect_to @studio, notice: 'Studio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @studio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studios/1
  # DELETE /studios/1.json
  def destroy
    @studio = Studio.find(params[:id])
    @studio.destroy

    respond_to do |format|
      format.html { redirect_to studios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/views/studios/_form.html.erb
<%= form_for(@studio) do |f| %>
  <% if @studio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@studio.errors.count, "error") %> prohibited this studio from being saved:</h2>

      <ul>
      <% @studio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/studios/edit.html.erb
<h1>Editing studio</h1>

<%= render 'form' %>

<%= link_to 'Show', @studio %> |
<%= link_to 'Back', studios_path %>

app/views/studios/index.html.erb
<h1>Listing studios</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @studios.each do |studio| %>
  <tr>
    <td><%= studio.name %></td>
    <td><%= link_to 'Show', studio %></td>
    <td><%= link_to 'Edit', edit_studio_path(studio) %></td>
    <td><%= link_to 'Destroy', studio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Studio', new_studio_path %>

app/views/studios/new.html.erb
<h1>New studio</h1>

<%= render 'form' %>

<%= link_to 'Back', studios_path %>

app/views/studios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @studio.name %>
</p>


<%= link_to 'Edit', edit_studio_path(@studio) %> |
<%= link_to 'Back', studios_path %>